spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  datasource:
    url: ${TEST_DB_URL:jdbc:tc:postgresql:16-alpine:///hotel_booking_service_test}
    username: ${TEST_DB_USERNAME:test}
    password: ${TEST_DB_PASSWORD:test}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate :
        format_sql: true


---

jwt:
  secretKey: ${JWT_SECRET_KEY:test-secret-key-only-for-testing-purposes-123}

cloudinary:
  cloud-name: test
  api-key: test
  api-secret: test
