spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  datasource:
    url: ${TEST_DB_URL:jdbc:h2:mem:hotel_booking_service_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${TEST_DB_USERNAME:sa}
    password: ${TEST_DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate :
        format_sql: true


---

jwt:
  secretKey: ${JWT_SECRET_KEY:test-secret-key-only-for-testing-purposes-123}

cloudinary:
  cloud-name: test
  api-key: test
  api-secret: test
