services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - PROD_DB_URL=jdbc:mysql://${RDS_ENDPOINT}:3306/hotel_booking
      - PROD_DB_USER=${DB_USER}
      - PROD_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET_KEY=super_secret_key_for_hotel_booking_app_12345
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"