[app_servers]
47.129.242.247 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/hotel-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
13.229.229.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/hotel-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[monitoring_server]
13.250.125.81 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/hotel-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'