export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8080/api/v1";

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_EMAIL: "/auth/resend",
    REFRESH_TOKEN: "/auth/refresh",
    SESSIONS: "/auth/sessions",
  },
  USERS: "/users",
  HOTELS: "/hotels",
  HOTELS_PUBLIC: "/hotels/public",
  ROOM_TYPES: "/room-types",
  BOOKINGS_ME: "/bookings/me",
  AMENITIES: "/amenities",
  BANNERS: "/banners",
  ADMIN_BANNERS: "/admin/banners",
  NEWS: "/news",
  ADMIN_NEWS: "/admin/news",
  PROMOTIONS: "/promotions",
  PROMOTIONS_PUBLIC: "/promotions/public",
  CONTACT: "/contact",
  ADMIN_CONTACTS: "/admin/contacts",
  PERMISSIONS: "/permissions",
  ROLES: "/roles",
  ACTIONS: "/actions",
  DASHBOARD: "/dashboard",
  UPLOAD: "/upload",
} as const;
