export const MESSAGES = {
  NETWORK_ERROR: "Network error - cannot reach API server.",
  FORBIDDEN: "You do not have permission to access this feature.",
  MOCK_MODE: "Mock mode is enabled.",
  OAUTH_TODO: "Google OAuth is TODO-safe until backend support is available.",
  AUTH: {
    VERIFY_EMAIL_FAILED: "Failed to verify email.",
    VERIFY_EMAIL_EXPIRED: "Verification email expired.",
  },
  USER: {
    UPDATE_SUCCESS: "User updated successfully.",
    UPDATE_FAILED: "Failed to update user.",
    UPDATE_PROFILE_SUCCESS: "Profile updated successfully.",
    UPDATE_PROFILE_FAILED: "Failed to update profile.",
    UPDATE_ROLE_SUCCESS: "Role updated successfully.",
    UPDATE_ROLE_FAILED: "Failed to update role.",
    UPDATE_ACTION_SUCCESS: "Action updated successfully.",
    UPDATE_ACTION_FAILED: "Failed to update action.",
    ASSIGN_ROLE_SUCCESS: "Role assigned successfully.",
    ASSIGN_ROLE_FAILED: "Failed to assign role.",
    DELETE_SUCCESS: "User deleted successfully.",
    DELETE_FAILED: "Failed to delete user.",
    MISSING_ROLE: "Missing role.",
    MISSING_ACTION: "Missing action.",
  },
} as const;
